services:
# FRONTEND
  router:
    build: router
    networks:
      - frontend

  dashboard:
    build: dashboard
    networks:
      - frontend
    ports:
      - 9091:8080
    develop:
      watch:
        - path: dashboard/package.json
          action: rebuild
        - path: dashboard/
          action: sync
          target: /home/node/app

# BACKEND BRIDGE
  search:
    build: api
    networks:
      - frontend
      - backend

# BACKEND
  rethinkdb:
    build: db
    networks:
      - backend
  
  cache:
    build: db/cache
    networks:
      - backend

networks:
  frontend:
  backend:
