services:
  dashboard:
    build: ./dashboard
    ports:
      - 9091:8080
    volumes:
      - ./dashboard:/home/node/app:rw
      - /home/node/app/node_modules
      - /home/node/app/.svelte-kit
    working_dir: /home/node/app
    command: yarn dev